name: delta
description:  "Twisted City Life"

environment:
  sdk: '>=2.0.0'

dependencies:
  sprintf: any
  js: ">= 0.6.1"
  chronosgl: "< 4.0.0"
  #chronosgl:
  #  path: ../ChronosGL

  vector_math: ">=2.0.5 <3.0.0"

dev_dependencies:
  build_runner: any
  build_test: any
  build_web_compilers: any

